#ddev-generated
services:

  w3c-validator:
    image: ghcr.io/validator/validator:latest
    # No support for ARM yet.
    # Feature request: https://github.com/validator/validator/issues/1545
    platform: linux/amd64
    container_name: ddev-${DDEV_SITENAME}-w3c-validator
    external_links:
      - ddev-router:${DDEV_SITENAME}.${DDEV_TLD}
    ports:
      - "8888:8888"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

    volumes:
    - ".:/mnt/ddev_config"
