#ddev-generated
services:
  w3c-validator:
    image: ghcr.io/validator/validator:latest
    container_name: ddev-${DDEV_SITENAME}-addon-template
    command: tail -f /dev/null
    networks: [default, ddev_default]
    restart: "no"
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

    volumes:
    - ".:/mnt/ddev_config"
